AspEndProject/Models/ServiceContent.cs
namespace AspEndProject.Models
{
    public class ServiceContent : BaseEntity
    {
        public string Image { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}

AspEndProject/ViewModels/ServiceContent/ServiceContentCreateVM.cs
using System.ComponentModel.DataAnnotations;

namespace AspEndProject.ViewModels.ServiceContent
{
    public class ServiceContentCreateVM
    {
        [Required]
        [MaxLength(25, ErrorMessage = "Max Length is 25")]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public IFormFile? Image { get; set; }
    }
}

AspEndProject/ViewModels/ServiceContent/ServiceContentDetailVM.cs
using System.ComponentModel.DataAnnotations;

namespace AspEndProject.ViewModels.ServiceContent
{
    public class ServiceContentDetailVM
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(25, ErrorMessage = "Max Length is 25")]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string Image { get; set; }
    }
}

AspEndProject/ViewModels/ServiceContent/ServiceContentUpdateVM.cs
using System.ComponentModel.DataAnnotations;

namespace AspEndProject.ViewModels.ServiceContent
{
    public class ServiceContentUpdateVM
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(25, ErrorMessage = "Max Length is 25")]
        public string? Title { get; set; }
        [Required]
        public string? Description { get; set; }
        public string? Image { get; set; }
        public IFormFile? Photo { get; set; }
    }
}

AspEndProject/ViewModels/ServiceContents/ServiceContentCreateVM.cs
using System.ComponentModel.DataAnnotations;

namespace AspEndProject.ViewModels.ServiceContents
{
    public class ServiceContentCreateVM
    {
        [Required]
        [MaxLength(25, ErrorMessage = "Max Length is 25")]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public IFormFile? Image { get; set; }
    }
}

AspEndProject/ViewModels/ServiceContents/ServiceContentDetailVM.cs
using System.ComponentModel.DataAnnotations;

namespace AspEndProject.ViewModels.ServiceContents
{
    public class ServiceContentDetailVM
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(25, ErrorMessage = "Max Length is 25")]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string Image { get; set; }
    }
}

AspEndProject/ViewModels/ServiceContents/ServiceContentUpdateVM.cs
using System.ComponentModel.DataAnnotations;

namespace AspEndProject.ViewModels.ServiceContents
{
    public class ServiceContentUpdateVM
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(25, ErrorMessage = "Max Length is 25")]
        public string? Title { get; set; }
        [Required]
        public string? Description { get; set; }
        public string? Image { get; set; }
        public IFormFile? Photo { get; set; }
    }
}

AspEndProject/Areas/Admin/Controllers/ServiceContentController.cs
using AspEndProject.DAL;
using AspEndProject.Helpers.Extentions;
using AspEndProject.Models;
using AspEndProject.ViewModels.ServiceContents;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AspEndProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ServiceContentController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;
        public ServiceContentController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        [Authorize(Roles = "SuperAdmin, Admin")]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<ServiceContent> serviceContent = await _context.ServiceContents.ToListAsync();
            return View(serviceContent);
        }
        [Authorize(Roles = "SuperAdmin, Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "SuperAdmin, Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ServiceContentCreateVM create)
        {
            if (!ModelState.IsValid) return View();

            if (!create.Image.CheckFileType("image/"))
            {
                ModelState.AddModelError("Image", "File must be Image Format");
                return View();
            }
            if (!create.Image.CheckFileSize(200))
            {

                ModelState.AddModelError("Image", "Max File Capacity mut be 300KB");
                return View();
            }
            string fileName = Guid.NewGuid().ToString() + "-" + create.Image.FileName;
            string path = Path.Combine(_env.WebRootPath, "img", fileName);
            await create.Image.SaveFileToLocalAsync(path);
            await _context.ServiceContents.AddAsync(new ServiceContent
            {
                Image = fileName,
                Title = create.Title,
                Description = create.Description
            });
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "SuperAdmin, Admin")]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id is null) return BadRequest();
            ServiceContent serviceContent = await _context.ServiceContents.Where(c => c.Id == id).FirstOrDefaultAsync();
            if (serviceContent == null) return NotFound();
            ServiceContentDetailVM model = new()
            {
                Id = serviceContent.Id,
                Title = serviceContent.Title,
                Image = serviceContent.Image,
                Description = serviceContent.Description,

            };
            return View(model);
        }
        [Authorize(Roles = "SuperAdmin, Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) return BadRequest();

            ServiceContent serviceContent = await _context.ServiceContents.Where(c => c.Id == id).FirstOrDefaultAsync();

            if (serviceContent is null) return NotFound();

            serviceContent.Image.DeleteFile(_env.WebRootPath, "img");

            _context.ServiceContents.Remove(serviceContent);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "SuperAdmin, Admin")]
        public async Task<IActionResult> Update(int id)
        {
            if (id == null) return BadRequest();
            ServiceContent serviceContent = await _context.ServiceContents.Where(c => c.Id == id).FirstOrDefaultAsync();
            if (serviceContent == null) return NotFound();

            return View(new ServiceContentUpdateVM
            {
                Image = serviceContent.Image,
                Title = serviceContent.Title,
                Description = serviceContent.Description
            });


        }
        [Authorize(Roles = "SuperAdmin, Admin")]
        [HttpPost]
        public async Task<IActionResult> Update(int id, ServiceContentUpdateVM request)
        {
            ServiceContent serviceContent = await _context.ServiceContents.Where(c => c.Id == id).FirstOrDefaultAsync();
            if (!ModelState.IsValid)
            {
                request.Image = serviceContent.Image;
                return View(request);
            }

            if (request.Photo != null)
            {
                if (!request.Photo.CheckFileSize(200))
                {
                    ModelState.AddModelError("Photo", "Image size must be 200kb");
                    return View(request.Photo);
                }

                if (!request.Photo.CheckFileType("image/"))
                {
                    ModelState.AddModelError("Photo", "Image format is wrong");
                    return View(request.Photo);
                }
                FileExtentions.DeleteFileFromLocalAsync(Path.Combine(_env.WebRootPath, "img"), serviceContent.Image);

                string fileName = Guid.NewGuid().ToString() + "-" + request.Photo.FileName;
                string path = Path.Combine(_env.WebRootPath, "img", fileName);
                await request.Photo.SaveFileToLocalAsync(path);

                serviceContent.Image = fileName;
            }

            if (serviceContent == null) { return NotFound(); }

            serviceContent.Title = request.Title;
            serviceContent.Description = request.Description;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));

        }
    }
}

AspEndProject/Areas/Admin/Views/ServiceContent/Create.cshtml
@model ServiceContentCreateVM


<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create ServiceContent</h4>
            <form class="forms-sample" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="Title">Title</label>
                    <input asp-for="Title" type="text" class="form-control" placeholder="Title">
                    <span class="text-danger mt-2" asp-validation-for="Title"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description">Description</label>
                    <input asp-for="Description" type="text" class="form-control" placeholder="Description">
                    <span class="text-danger mt-2" asp-validation-for="Description"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Image">Image</label>
                    <input asp-for="Image" class="form-control">
                    <span class="text-danger mt-2" asp-validation-for="Image"></span>
                </div>
                <button type="submit" class="btn btn-gradient-primary me-2">Submit</button>
                <a class="btn btn-light" asp-area="Admin" asp-controller="ServiceContent" asp-action="Index">Back</a>
            </form>
        </div>
    </div>
</div>

AspEndProject/Areas/Admin/Views/ServiceContent/Detail.cshtml
@model ServiceContentDetailVM

<div class="container mt-5 mx-3">

    <h3><img  src="~/img/@Model.Image" /></h3>
    <h3> Title: @Model.Title </h3>
    <h3> Description: @Model.Description </h3>
    
    <div class=mt-4>

        <a class="btn btn-primary" asp-area="Admin" asp-controller="ServiceContent" asp-action="Index">Back</a>
        <a class="btn btn-primary" asp-area="Admin" asp-controller="ServiceContent" asp-route-id="@Model.Id" asp-action="Update">Update</a>
        <a class="btn btn-danger" asp-area="Admin" asp-controller="ServiceContent" asp-route-id="@Model.Id" asp-action="Delete">Delete</a>
    </div>
</div>

AspEndProject/Areas/Admin/Views/ServiceContent/Index.cshtml
@model List<ServiceContent>

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <a class="btn btn-success" asp-area="Admin" asp-controller="ServiceContent" asp-action="Create">Create ServiceContent</a>


            <table class="table table-striped">
                <thead>
                    <tr>
                        <th> Image </th>
                        <th> Title </th>
                        <th> Description </th>
                        <th> Settings </th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>

                            <td> <img src="~/img/@item.Image"> </td>
                            <td> @item.Title </td>
                            <td> @item.Description </td>
                            <td>
                                <a class="btn btn-info" asp-area="Admin" asp-controller="ServiceContent" asp-route-id="@item.Id" asp-action="Detail">Detail</a>
                                <a class="btn btn-primary" asp-area="Admin" asp-controller="ServiceContent" asp-route-id="@item.Id" asp-action="Update">Update</a>
                                <a class="btn btn-danger" asp-area="Admin" asp-controller="ServiceContent" asp-route-id="@item.Id" asp-action="Delete">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

AspEndProject/Areas/Admin/Views/ServiceContent/Update.cshtml
@model ServiceContentUpdateVM


<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Update ServiceContent</h4>
            <img src="~/img/@Model.Image"/>
            <form class="forms-sample" method="post" asp-action="Update" enctype="multipart/form-data">
               <div class="form-group">
                    <label asp-for="Title">Title</label>
                    <input asp-for="Title" type="text" class="form-control" placeholder="Title">
                    <span class="text-danger mt-2" asp-validation-for="Title"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description">Description</label>
                    <input asp-for="Description" type="text" class="form-control" placeholder="Description">
                    <span class="text-danger mt-2" asp-validation-for="Description"></span>
                </div>
                <div class="mt-3 form-group">
                    <label asp-for="Photo">Image</label>
                    <input asp-for="Photo" class="form-control">
                    <span class="text-danger mt-2" asp-validation-for="Photo"></span>
                </div>
                
                <button type="submit" class="btn btn-gradient-primary me-2">Submit</button>
                <a class="btn btn-light" asp-area="Admin" asp-controller="ServiceContent" asp-action="Index">Back</a>
            </form>
        </div>
    </div>
</div>