AspEndProject/Models/SliderInfo.cs
namespace AspEndProject.Models
{
    public class SliderInfo : BaseEntity
    {
        public string Title { get; set; }
        public string SubTitle { get; set; }
    }
}

AspEndProject/ViewModels/SliderInfos/SliderInfoCreateVM.cs
using System.ComponentModel.DataAnnotations;

namespace AspEndProject.ViewModels.SliderInfos
{
    public class SliderInfoCreateVM
    {
        [Required]
        public string Title { get; set; }
        [Required]
        public string SubTitle { get; set; }
    }
}

AspEndProject/ViewModels/SliderInfos/SliderInfoDetailVM.cs
namespace AspEndProject.ViewModels.SliderInfos
{
    public class SliderInfoDetailVM
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
    }
}

AspEndProject/ViewModels/SliderInfos/SliderInfoUpdateVM.cs
using System.ComponentModel.DataAnnotations;

namespace AspEndProject.ViewModels.SliderInfos
{
    public class SliderInfoUpdateVM
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string SubTitle { get; set; }
    }
}

AspEndProject/Areas/Admin/Controllers/SliderInfoController.cs
using AspEndProject.DAL;
using AspEndProject.Models;
using AspEndProject.ViewModels.SliderInfos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AspEndProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SliderInfoController : Controller
    {
        private readonly AppDbContext _context;
        public SliderInfoController(AppDbContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "SuperAdmin, Admin")]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<SliderInfo> sliderInfos = await _context.SliderInfos.ToListAsync();
            return View(sliderInfos);
        }
        [Authorize(Roles = "SuperAdmin, Admin")]
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [Authorize(Roles = "SuperAdmin, Admin")]
        public async Task<IActionResult> Detail(int? id)
        {
            if (id is null) return BadRequest();
            SliderInfo sliderInfo = await _context.SliderInfos.Where(c => c.Id == id).FirstOrDefaultAsync();
            if (sliderInfo == null) return NotFound();
            SliderInfoDetailVM model = new()
            {
                Id = sliderInfo.Id,
                Title = sliderInfo.Title,
                SubTitle = sliderInfo.SubTitle
            };
            return View(model);
        }
        [Authorize(Roles = "SuperAdmin, Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SliderInfoCreateVM sliderInfo)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            bool existSliderInfo = await _context.SliderInfos.AnyAsync(m => m.Title == sliderInfo.Title && m.SubTitle == sliderInfo.SubTitle);
            if (existSliderInfo)
            {
                ModelState.AddModelError("Title", "These inputs already exist");
            }

            await _context.SliderInfos.AddAsync(new SliderInfo { Title = sliderInfo.Title, SubTitle = sliderInfo.SubTitle });
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }



        [Authorize(Roles = "SuperAdmin, Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return BadRequest();
            SliderInfo sliderInfo = await _context.SliderInfos.FirstOrDefaultAsync(m => m.Id == id);

            if (sliderInfo == null) return NotFound();

            _context.SliderInfos.Remove(sliderInfo);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }


        [Authorize(Roles = "SuperAdmin, Admin")]
        [HttpGet]
        public async Task<IActionResult> Update(int? id)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (id == null) return BadRequest();
            SliderInfo sliderInfo = await _context.SliderInfos.FirstOrDefaultAsync(m => m.Id == id);

            if (sliderInfo == null) return NotFound();

            return View(new SliderInfoUpdateVM
            {
                Title = sliderInfo.Title,
                SubTitle = sliderInfo.SubTitle
            });

        }

        [Authorize(Roles = "SuperAdmin, Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(SliderInfoUpdateVM sliderInfo, int? id)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (id == null) return BadRequest();
            SliderInfo existSliderInfo = await _context.SliderInfos.FirstOrDefaultAsync(m => m.Id == id);

            if (sliderInfo == null) return NotFound();

            existSliderInfo.Title = sliderInfo.Title;
            existSliderInfo.SubTitle = sliderInfo.SubTitle;
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");

        }
    }
}

AspEndProject/Areas/Admin/Views/SliderInfo/Create.cshtml
@model SliderInfoCreateVM


<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create SliderInfo</h4>
            <form class="forms-sample" method="post" enctype="multipart/form-data">
                 <div class="form-group">
                    <label asp-for="Title" >Title</label>
                    <input asp-for="Title" type="text" class="form-control" placeholder="Title">
                    <span  class="text-danger mt-2" asp-validation-for="Title"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SubTitle">SubTitle</label>
                    <input asp-for="SubTitle" type="text" class="form-control" placeholder="SubTitle">
                    <span  class="text-danger mt-2" asp-validation-for="SubTitle"></span>
                </div>
                <button type="submit" class="btn btn-gradient-primary me-2">Submit</button>
                <a class="btn btn-light" asp-area="Admin" asp-controller="SliderInfo" asp-action="Index">Back</a>
            </form>
        </div>
    </div>
</div>

AspEndProject/Areas/Admin/Views/SliderInfo/Detail.cshtml
@model SliderInfoDetailVM

<div class="container mt-5 mx-3">

    <h3> Title: @Model.Title </h3>
    <h3> SubTitle: @Model.SubTitle </h3>
    
    <div class=mt-4>

        <a class="btn btn-primary" asp-area="Admin" asp-controller="SliderInfo" asp-action="Index">Back</a>
        <a class="btn btn-primary" asp-area="Admin" asp-controller="SliderInfo" asp-route-id="@Model.Id" asp-action="Update">Update</a>
        <a class="btn btn-danger" asp-area="Admin" asp-controller="SliderInfo" asp-route-id="@Model.Id" asp-action="Delete">Delete</a>
    </div>
</div>

AspEndProject/Areas/Admin/Views/SliderInfo/Index.cshtml
@model List<SliderInfo>

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <a class="btn btn-success" asp-area="Admin" asp-controller="SliderInfo" asp-action="Create">Create SliderInfo</a>


            <table class="table table-striped">
                <thead>
                    <tr>
                        <th> Title </th>
                        <th> SubTitle </th>
                        <th> Settings </th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td> @item.Title </td>
                            <td> @item.SubTitle </td>
                            <td>
                                <a class="btn btn-info" asp-area="Admin" asp-controller="SliderInfo" asp-route-id="@item.Id" asp-action="Detail">Detail</a>
                                <a class="btn btn-primary" asp-area="Admin" asp-controller="SliderInfo" asp-route-id="@item.Id" asp-action="Update">Update</a>
                                <a class="btn btn-danger" asp-area="Admin" asp-controller="SliderInfo" asp-route-id="@item.Id" asp-action="Delete">Delete</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

AspEndProject/Areas/Admin/Views/SliderInfo/Update.cshtml
@model SliderInfoUpdateVM


<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Update SliderInfo</h4>
            <form class="forms-sample" method="post" asp-action="Update" enctype="multipart/form-data">
               <div class="form-group">
                    <label asp-for="Title" >Title</label>
                    <input asp-for="Title" type="text" class="form-control" placeholder="Name">
                    <span  class="text-danger mt-2" asp-validation-for="Title"></span>
                </div>
                <div class="mt-3 form-group">
                    <label asp-for="SubTitle">SubTitle</label>
                    <input asp-for="SubTitle" class="form-control">
                    <span class="text-danger mt-2" asp-validation-for="SubTitle"></span>
                </div>
                
                <button type="submit" class="btn btn-gradient-primary me-2">Submit</button>
                <a class="btn btn-light" asp-area="Admin" asp-controller="SliderInfo" asp-action="Index">Back</a>
            </form>
        </div>
    </div>
</div>